name: CI/CD Pipeline for ML model

on:
  push:
    branches:
      - main  # ou la branche que tu veux utiliser

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "dckr_pat_S3OJ1ph-7p_zRoCfpL71ZToMOGQ" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t samyamine/td-ml-for-embedded-1:latest .

      - name: Push Docker image
        run: docker push samyamine/td-ml-for-embedded-1:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Connect to SSH
        run: |
          sshpass -p "${{ secrets.VM_SSH_KEY }}" ssh ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} -o StrictHostKeyChecking=no << 'EOF'
            if [ ! -d "/home/ubuntu/samy.amine" ]; then
              mkdir /home/ubuntu/samy.amine
            fi
            docker pull ${{ secrets.DOCKER_USERNAME }}/td-ml-for-embedded-1:latest
            docker rm /td-ml-for-embedded-1
            docker run -d -p 8067:8067 --name td-ml-for-embedded-1 ${{ secrets.DOCKER_USERNAME }}/td-ml-for-embedded-1:latest
          EOF
