name: CI/CD Pipeline for ML model

on:
  push:
    branches:
      - main  # ou la branche que tu veux utiliser

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "dckr_pat_S3OJ1ph-7p_zRoCfpL71ZToMOGQ" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t samyamine/td-ml-for-embedded-1:latest .

      - name: Push Docker image
        run: docker push samyamine/td-ml-for-embedded-1:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH to VM
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker pull samyamine/td-ml-for-embedded-1:latest
            docker stop <container_name> || true
            docker run -d -p 80:80 --name <container_name> samyamine/td-ml-for-embedded-1:latest
